### ISSUE TITLE
DJI Mini 2 Photo rotation angle (azimuth)

### ISSUE THREAD

**Issue by jorgealmerio** [verticalphotoplacer/VerticalPhotoPlacerPlugin#1]
Hi,

I was able to use the plugin and loaded the photos on the right place in Qgis enviroment, but the rotation of the photos was wrong.

The photos was placed horizontally. it would have almost a 30 degrees angle to be properly aligned.

Is there a way the plugin can read the photo rotation angle (azimuth)?

**Comment by mdchuc** [comment]
Hi, 

Yes, VPP uses the gimbal yaw angle to determine a photo's rotation on map.
Probably, I guess the problem may be gimbal yaw angle, I will update VPP to use flight yaw angle instead.

If possible, could you send me some of your photos (email: chuc92man@gmail.com)? 
I will check it and see if there should be some other fixes.

Thanks,

**Comment by chuc92man** [comment]
Hi,

I check again, perhaps it is because of gimbal yaw angle.
I will update VPP to use Flight yaw angle instead of gimbal yaw angle.

Regards,

**Comment by jorgealmerio** [comment]
Hi,

I am sending 3 JPG files. I also have the DNG format if you prefer. It's RAW format, is bigger size and not supported to send here.

![DJI_0013](https://user-images.githubusercontent.com/16169268/135929321-3c4009b5-a334-49e2-9f23-00ebf5605e40.JPG)
![DJI_0015](https://user-images.githubusercontent.com/16169268/135929358-288a94e4-20a6-4616-935f-5b8c8db091d5.JPG)
![DJI_0014](https://user-images.githubusercontent.com/16169268/135929344-028f2b42-5b1a-4a0b-9238-e3715d37d9e6.JPG)

**Comment by mdchuc** [comment]
Hi, 

I checked it. The problem is gimbal yaw angle.
Please update your VPP to v0.2.
Your photo is rotated in the right angle in VPP v0.2

![Capture](https://user-images.githubusercontent.com/13627771/135937085-40a02e4d-b433-4790-8c3c-fcaf6bca5ddc.PNG)

Thanks

**Comment by jorgealmerio** [comment]
Good Job! Working Now! Can close this Issue!
Thank you!

**Comment by mdchuc** [comment]
Thanks a lot.
